---
abstract: 'Flip text upside-down using Unicode'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-UpsideDown
provides:
  Text::UpsideDown:
    file: lib/Text/UpsideDown.pm
    version: 1.100820
requires:
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  charnames: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-UpsideDown
  homepage: http://search.cpan.org/dist/Text-UpsideDown/
  repository: http://github.com/hanekomu/Text-UpsideDown
version: 1.100820
